name: Deploy to custom linux server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.16.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Transfer build files to VPS
        # You may pin to the exact commit or the version.
        # uses: appleboy/scp-action@6d1fc191a822daa12faa45f3a985413f995ff5c5
        uses: appleboy/scp-action@v0.1.7
        with:
          debug: true
          # scp remote host
          host: ${{ secrets.SSH_REMOTE_HOST }}
          # ssh remote port
          port: ${{ secrets.SSH_REMOTE_PORT }}
          # ssh remote user
          username: ${{ secrets.SSH_REMOTE_USER }}
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.SSH_REMOTE_KEY }}
          passphrase: ${{ secrets.SSH_REMOTE_PASSPHRASE }}
          source: "./dist"
          target: "/var/www/static/portfolio"
